<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Completed</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="../styles.css">
</head>
<body class="d-flex vh-100 vw-100">
<div class="w-50 my-auto mx-auto p-4 rounded text-center mainBox">
    <h1 class="my-4 fs-1"><u>COMPLETED TASKS</u></h1>
<div class="d-flex flex-column align-items-center mb-3">
<?php
    if (count($tasks) === 0){
        echo '<p>No Completed Tasks!</p>';
    }
    else {
        foreach ($tasks as $task){
            echo '<div class="d-flex my-4 flex-row text-start justify-content-between w-50">';
            echo '<h2 class="fs-5 mx-4 my-0">' . $task['task_name'] . '</h2>';
            echo '<form method="post">';
            echo '<button name="delete" type="submit" value=' . $task['id'] . '>&#10008;</button>';
            echo '</form>';
            echo '</div>';
        }
    }
?>
</div>
<a href="/">HOME</a>
</div>
</body>
</html>