<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Edit</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="../styles.css">
</head>
<body class="d-flex vh-100 vw-100">
<div class="w-50 my-auto mx-auto p-4 rounded text-center mainBox">
    <h1 class="my-4 fs-1"><u>EDIT TASK</u></h1>
<form method="post" class="my-4">
    <label for="editTask">Edit Task:</label>
    <?= '<input name = "editedTask" id="editTask" value="' . $task['task_name'] . '">'?>
    <button type="submit">UPDATE</button>
</form>
<a class='d-block' href="/completed">SHOW COMPLETED</a>
<a class='d-block' href="/">HOME</a>
</div>
</body>
</html>