<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>HOME</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="../styles.css">
</head>
<body class="d-flex vh-100 vw-100">
<div class="w-50 my-auto mx-auto p-4 rounded text-center mainBox">
    <h1 class="my-4"><u>TODO List</u></h1>
    <form method="post" class="my-4">
        <label for="addTask">Add Task:</label>
        <input id="addTask" type="text" name="taskName">
        <input type="submit" value="add">
    </form>
    <div class="d-flex flex-column align-items-center mb-3">
    <?php
    if (count($tasks) === 0) {
        echo '<p>No Active Tasks!</p>';
    }
    else {
        foreach ($tasks as $task) {
            echo '<div class="d-flex my-4 flex-row justify-content-between w-50">';
            echo '<h2 class="fs-5 mx-4 my-0">' . $task['task_name'] . ':</h2>';
            echo '<span class="d-flex flex-row">';
            echo '<form method="post">';
            echo '<button class="mx-2" name="done" type="submit" value=' . $task['id'] . '>&#10004;</button>';
            echo '</form>';
            echo '<form action="/edit/' . $task['id'] . '"</form>';
            echo '<button type="submit">&#10000;</button>';
            echo '</span>';
            echo '</form>';
            echo '</div>';
        }
    }
    ?>
    </div>
    <a class="my-5" href="/completed">COMPLETED TASKS</a>
</div>
</body>
</html>